name: Test job
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/Checkout@v4

      - name: Run Script with Secret
        run: python .github/Scripts/TestScript01.py
        env:
          GITHUB_SECRET: ${{ secrets.TEST_SECRET}}
      - name: Run cat on test file
        run: cat test
      - name: Print goodbye
        run: echo "Done - bye!"

